language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - npm install $TYPESCRIPT

env:
  - TYPESCRIPT=typescript@1.6
  - TYPESCRIPT=typescript@next

node_js:
  - "0.12"
  - "iojs"
  - "4"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
